source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in ecko-plugins.gemspec
gemspec

group :test do
  gem 'pry'
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'faker', '~> 1.9.1'
  gem 'simplecov'
end
