# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ecko-plugins-sponsor.gemspec
gemspec

group :test do
  gem 'pry'
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'faker', '~> 1.9.1'
  gem 'simplecov'
end

gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
